# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-nline
version:      0.04
version_from: nline.pm
installdirs:  site
requires:
    PerlIO::eol:                   0.02
    XSLoader:                      0.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
